Update wait and lgtm

diff --git a/.github/workflows/create-tag-release.yml b/.github/workflows/create-tag-release.yml
--- a/.github/workflows/create-tag-release.yml
+++ b/.github/workflows/create-tag-release.yml
@@ -124,26 +124,90 @@ jobs:
       - name: Watching PR if Checks finished without errors
         id: wait-checks
         run:
-          gh pr checks  ${{ needs.create-pr.outputs.pr_number }}  --watch --fail-fast 
+          echo "skiping local check not present"
+          # gh pr checks  ${{ needs.create-pr.outputs.pr_number }}  --watch --fail-fast 
         env:     
           GH_TOKEN: ${{ github.TOKEN}}
-
-
-  merge-pr:
-    needs: [ check-prev-tag,create-pr, wait-checks ]
+  
+  comment-lgtm:
+    needs: wait-checks
     runs-on: ubuntu-latest
+    steps:
+      - name: Add comment to trigger lgtm label
+        if: ${{ steps.wait-checks.conclusion == 'success' }}
+        run: |
+          gh pr comment ${{ needs.create-pr.outputs.pr_number }} --body "/lgtm"
+        env:
+          GH_TOKEN: ${{ github.TOKEN }}
+
+  wait-lgtm:
+    runs-on: ubuntu-latest
+    needs: [ wait-checks, comment-lgtm ]
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
         with:
-          ref: ${{ github.ref }}
+          fetch-depth: 0
+
+      - name: Wait for lgtm label
+        id: wait-lgtm
+        run: |
+          for i in {1..60}; do
+            labels=$(gh pr view ${{ needs.create-pr.outputs.pr_number }} --json labels --jq '.labels[].name')
+            if echo "$labels" | grep -qw "lgtm"; then
+              echo "has_lgtm=true" >> $GITHUB_ENV
+              break
+            else
+              echo "Waiting for lgtm label... (attempt $i)"
+              sleep 60
+            fi
+          done
+          if [ "${has_lgtm}" != "true" ]; then
+            echo "Error: 'lgtm' label not found after waiting."
+            exit 1
+          fi
+        env:
+          GH_TOKEN: ${{ github.TOKEN }}
+
+  merge-pr:
+    needs: [ check-prev-tag,create-pr, wait-checks,comment-lgtm,wait-lgtm ]
+    runs-on: ubuntu-latest
+    steps:
+       - name: Merge PR if LGTM label exists
+         if: env.has_lgtm == 'true'
+         run: |
+          gh pr merge ${{ needs.create-pr.outputs.pr_number }} --merge --auto
+         env:
+          GH_TOKEN: ${{ github.TOKEN }}
+      # - name: Check if PR has lgtm label
+      #   id: check_lgtm
+      #   run: |
+      #     labels=$(gh pr view ${{ needs.create-pr.outputs.pr_number }} --json labels --jq '.labels[].name')
+      #     if echo "$labels" | grep -qw "lgtm"; then
+      #       echo "has_lgtm=true" >> $GITHUB_ENV
+      #     else
+      #       echo "has_lgtm=false" >> $GITHUB_ENV
+      #   env:
+      #     GH_TOKEN: ${{ github.TOKEN }}
+
+      # - name: Merge PR
+      #   if: env.has_lgtm == 'true'
+      #   run: gh pr merge ${{ needs.create-pr.outputs.pr_number }} --merge --auto
+      #   env:
+      #     GH_TOKEN: ${{ github.TOKEN }}
+
+
+      # - name: Checkout code
+      #   uses: actions/checkout@v4
+      #   with:
+      #     ref: ${{ github.ref }}
   
-      - name: Enable Pull Request Automerge
-        if: ${{ needs.wait-checks.result == 'success' }}
-        run: gh pr merge --merge --auto  ${{ needs.create-pr.outputs.pr_number }} 
-        env:     
-           GH_TOKEN: ${{ github.TOKEN}}
-   
+      # - name: Enable Pull Request Automerge
+      #   if: ${{ needs.wait-checks.result == 'success' }}
+      #   run: gh pr merge --merge --auto  ${{ needs.create-pr.outputs.pr_number }} 
+      #   env:     
+      #      GH_TOKEN: ${{ github.TOKEN}}
+     
       
 
   changelog:
